site_name: 'Ultimate UNRAID Dashboard'
site_description: 'Unofficial Documentation'
site_author: 'LTM'
docs_dir: docs/
repo_name: 'Edit on GitHub'
repo_url: 'https://github.com/LilTrublMakr/Media-Servarr-List/'

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

plugins:
  - search
  - macros
  - roamlinks
  - mkdocs-versioning:
      version: 1.5.0

theme:
  name: 'material'

extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://forums.unraid.net/topic/96895-ultimate-unraid-dashboard-uud/
      name: UNRAID Forum Topic

extra_css:
  - stylesheets/extra.css

nav:
  - Ultimate UNRAID Dashboard: index.md
  - Install: install.md
  - Contribute: contribute.md
  - News: news.md
  - Version: '../'


copyright: Copyright &copy; 2021 - LTM Tech